services:
  - type: web
    name: web-gpt-tanjungpriok-api
    runtime: node
    rootDir: server
    plan: free
    buildCommand: npm install
    startCommand: npm run migrate && npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"
      - key: DB_PORT
        value: "5432"
      - key: DB_SSL
        value: "true"
      - key: DB_SSL_REJECT_UNAUTHORIZED
        value: "true"
      - key: JWT_EXPIRES_IN
        value: 1d
      - key: DB_HOST
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: CLOUDINARY_FOLDER
        value: gpt-tanjungpriok/articles
